language: python
python: 3.6
install:
  - pip install --upgrade --requirement requirements.txt
script:
  - make html && rm --force --recursive _build
deploy:
  on:
    branch: main
  provider: script
  script: 'git remote set-url origin "https://$USERNAME:$PASSWORD@github.com/cs50/cs50.readthedocs.io.git" && git branch --delete rel || true && git checkout -b rel && git add --all --force && git commit --allow-empty --message "$(date) [skip ci]" && git push --force origin rel'
  skip_cleanup: true
