exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
host: 0.0.0.0
port: 8080
markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "autolinkfilter"
    - "rougefilter"
