exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
gems:
  - jekyll-optional-front-matter
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-html-pipeline
host: 0.0.0.0
port: 8080
markdown: HTMLPipeline
html_pipeline:
  filters:
    - "markdownfilter"
    - "autolinkfilter"
