exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
host: 0.0.0.0
markdown: kramdown
port: 8080
syntax_highlighter: rouge
