exclude: 
  - "docker-compose.yml"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "Makefile"
  - "README.md"
  - "TODO.md"
host: 0.0.0.0
kramdown:
  parse_block_html: true
  toc_levels: 2..6
markdown: kramdown
port: 8080
syntax_highlighter: rouge
